### ISSUE TITLE
Deregister User

### ISSUE THREAD

**Issue by Phoenixces** [Phoenixces/Blog-App-REST#25]

**Comment by Shivangi93090** [comment]
Can not directly deregister a user :
<img width="1273" alt="Screenshot 2024-11-30 at 9 51 53 PM" src="https://github.com/user-attachments/assets/52596429-94f3-4bfc-bf03-fd225165d4eb">
A writing blog typically does not require a user deregistration feature unless it is used within an organization that enforces specific terms or policies related to user accounts.
